apiVersion: v1
kind: ResourceQuota
metadata:
  name: badminton-website
  namespace: badminton-website
  labels:
    app.kubernetes.io/name: badminton-website
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 640Mi
    limits.cpu: "5"
    limits.memory: 1500Mi
